"""Duck Hunt OpenEnv Configuration"""

# SCREEN
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 500
FPS = 30

# TIMING
MATCH_DURATION_SECONDS = 30
MATCH_DURATION_FRAMES = MATCH_DURATION_SECONDS * FPS  # 900
ROUND_START_SECONDS = 2  # Auto-skip
DOG_SCENE_SECONDS = 2  # Auto-skip

# GAME STRUCTURE
MATCHES_PER_ROUND = 5
DUCKS_PER_MATCH = 2
BULLETS_PER_MATCH = 3
MAX_MISSES = 4  # Game over threshold

# DUCK
HITBOX_WIDTH = 81
HITBOX_HEIGHT = 75
SPEED_BASE = 4  # Minimum speed component
SPEED_VARIANCE = 2  # Added to base
# Speed = BASE+round to BASE+VARIANCE+round

# BOUNCE
BOUNCE_DY_MIN = -4
BOUNCE_DY_MAX = 4
BOUNCE_TOP_DY_MIN = 2
BOUNCE_TOP_DY_MAX = 4
BOUNCE_BOTTOM_DY_MIN = -4
BOUNCE_BOTTOM_DY_MAX = -2

# OPENENV SPECIFIC
FRAME_OUTPUT_SIZE = (512, 512)  # Resized for VLM
FRAMES_PER_OBSERVATION = 4  # Number of frames per observation (default)
FRAMES_PER_OBSERVATION_MIN = 2  # Minimum frames for random range
FRAMES_PER_OBSERVATION_MAX = 6  # Maximum frames for random range
MAX_HORIZON = 30  # Maximum horizon VLM can use
LATENCY_OPTIONS_MS = [100, 200, 300, 400, 500, 600]

# REWARDS
REWARD_HIT = 1.0
REWARD_DOUBLE_KILL = 2.5
REWARD_MISS = -0.3
REWARD_SHOOT_NOTHING = -0.5  # Shot when no duck flying
LAMBDA_HORIZON = 0.1  # Horizon penalty weight
BONUS_PERFECT_MATCH = 0.5
BONUS_PERFECT_ROUND = 2.0
